export const SET_TAB_KEY = 'ADMIN/SET_TAB_KEY';
export const SET_MODAL_SHOW = 'ADMIN/SET_MODAL_SHOW';
export const SET_AUTH_USER_DATA = 'ADMIN/SET_AUTH_USER_DATA';
export const SET_SHOW_ALERT = 'ADMIN/SET_SHOW_ALERT';
export const ADD_NEW_ORDER = 'ORDER/ADD_NEW_ORDER';
export const EDIT_ORDER = 'ORDER/EDIT_ORDER';
